language: c
sudo: false

compiler:
  - clang
  - gcc

os:
  - linux
  - osx
  
addons:
  apt:
    packages:
      - linux-headers-generic

before_script:
  - cd minivideo/build
  - cmake ..

script: make
