language: cpp
sudo: false

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

#osx_image: xcode9.1

install:
  # /usr/bin/gcc is v4.8 by default, but newer gcc package (gcc-X prefixed) is available.
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then if [ "$CXX" == "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi; fi;
  # /usr/bin/clang is v3.4 by default, and newer clang package (clang-X.Y prefixed) is available.
  #- if [ "$TRAVIS_OS_NAME" == "linux" ]; then if  [ "$CXX" = "clang++" ]; then export CXX="clang++-5.0" CC="clang-5.0"; fi; fi;

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - g++-7
      - clang-5.0
      - linux-headers-generic

before_script:
  - cd minivideo/build/
  - cmake ..

script:
   - make
