os:
  - linux
  - osx

dist: trusty
sudo: false

language: c

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - linux-headers-generic

before_script:
  - cd minivideo/build
  - cmake ..

script: make
