/*!
 * COPYRIGHT (C) 2010 Emeric Grange - All Rights Reserved
 *
 * This file is part of MiniVideo.
 *
 * MiniVideo is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * MiniVideo is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with MiniVideo.  If not, see <http://www.gnu.org/licenses/>.
 *
 * \file      cmake_defines.h
 * \author    Emeric Grange <emeric.grange@gmail.com>
 * \date      2010
 */

#ifndef CONFIG_H
#define CONFIG_H

// !!! DO NOT EDIT THIS FILE MANUALLY !!!
// !!! CHANGES WILL BE OVERWRITTEN BY CMAKE !!!
// cmake_defines.h.in is a template
// cmake_defines.h is filled-up by cmake from the template

/* ************************************************************************** */

#define minivideo_VERSION_MAJOR 4
#define minivideo_VERSION_MINOR 0
#define minivideo_VERSION_PATCH 0

#define ENDIANNESS     1234  //!< 1234 if the target system is little endian, 4321 for big endian

#define ENABLE_DEBUG      1  //!< Toggle debug and trace output
#define ENABLE_COLORS     1  //!< Toggle colored terminal output
#define ENABLE_STDINT     1  //!< Toggle C99 <stdint.h> usage
#define ENABLE_STDBOOL    1  //!< Toggle C99 <stdbool.h> usage

#define ENABLE_STBIMWRITE 1  //!< Toggle bundled stb_image_write support
#define ENABLE_JPEG       1  //!< Toggle external libjpeg support
#define ENABLE_PNG        1  //!< Toggle external libpng support

/* ************************************************************************** */
#endif /* CONFIG_H */
