/*!
 * COPYRIGHT (C) 2018 Emeric Grange - All Rights Reserved
 *
 * This file is part of MiniVideo.
 *
 * MiniVideo is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * MiniVideo is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with MiniVideo.  If not, see <http://www.gnu.org/licenses/>.
 *
 * \file      minivideo_settings.h
 * \author    Emeric Grange <emeric.grange@gmail.com>
 * \date      2016
 */

#ifndef minivideo_EXPORT_H
#define minivideo_EXPORT_H

// !!! EVERY TIMES CMAKE IS RUN, THIS FILE WILL BE REGENERATED !!!
// minivideo_export.h is generated by cmake 3.4+
// it contains minivideo_EXPORT macro, used to automate symbols export

/* ************************************************************************** */

#define minivideo_EXPORT

/* ************************************************************************** */
#endif // minivideo_EXPORT_H
