/*!
 * COPYRIGHT (C) 2016 Emeric Grange - All Rights Reserved
 *
 * This file is part of MiniVideo.
 *
 * MiniVideo is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * MiniVideo is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with MiniVideo.  If not, see <http://www.gnu.org/licenses/>.
 *
 * \file      minivideo_settings.h
 * \author    Emeric Grange <emeric.grange@gmail.com>
 * \date      2016
 */

#ifndef MINIVIDEO_SETTINGS_H
#define MINIVIDEO_SETTINGS_H

// !!! EVERY TIMES CMAKE IS RUN, THIS FILE WILL BE REGENERATED !!!
// minivideo_settings.h.in is the template
// minivideo_settings.h is generated by cmake from the template

/* ************************************************************************** */

// This is the "default settings" version of this file, you can edit it manually

#define ENABLE_DEBUG        1  //!< Toggle debug and trace output
#define ENABLE_COLORS       1  //!< Toggle colored terminal output

#define ENABLE_STBIMWRITE   1  //!< Toggle bundled stb_image_write support
#define ENABLE_WEBP         0  //!< Toggle external libwebp support
#define ENABLE_JPEG         0  //!< Toggle external libjpeg support
#define ENABLE_PNG          0  //!< Toggle external libpng support

#define ENABLE_MEMFD        1  //!< Enable memfd support for Linux

/* ************************************************************************** */
#endif // MINIVIDEO_SETTINGS_H
