/*!
 * COPYRIGHT (C) 2020 Emeric Grange - All Rights Reserved
 *
 * This file is part of MiniVideo.
 *
 * MiniVideo is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * MiniVideo is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with MiniVideo.  If not, see <http://www.gnu.org/licenses/>.
 *
 * \author    Emeric Grange <emeric.grange@gmail.com>
 * \date      2016
 */

#ifndef MINIVIDEO_SETTINGS_H
#define MINIVIDEO_SETTINGS_H
/* ************************************************************************** */

// "minivideo_settings.h.in" is the template file
// "minivideo_settings.h" is GENERATED by CMake from the template file

#define minivideo_VERSION_MAJOR     0
#define minivideo_VERSION_MINOR     15
#define minivideo_VERSION_PATCH     0

#define ENABLE_DEBUG                0       //!< Toggle debug and trace output
#define ENABLE_COLORS               ON      //!< Toggle colored terminal output

#define ENABLE_STB_IMAGE_WRITE      ON      //!< Toggle bundled stb_image_write support
#define ENABLE_AVIF                 OFF     //!< Toggle external libwebp support
#define ENABLE_WEBP                 OFF     //!< Toggle external libwebp support
#define ENABLE_JPEG                 OFF     //!< Toggle external libjpeg support
#define ENABLE_PNG                  OFF     //!< Toggle external libpng support

#define ENABLE_MEMFD                ON      //!< Enable memfd support for Linux

/* ************************************************************************** */
#endif // MINIVIDEO_SETTINGS_H
