/*!
 * COPYRIGHT (C) 2018 Emeric Grange - All Rights Reserved
 *
 * This file is part of MiniVideo.
 *
 * MiniVideo is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * MiniVideo is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with MiniVideo.  If not, see <http://www.gnu.org/licenses/>.
 *
 * \file      minivideo_settings.h
 * \author    Emeric Grange <emeric.grange@gmail.com>
 * \date      2016
 */

#ifndef MINIVIDEO_SETTINGS_H
#define MINIVIDEO_SETTINGS_H
/* ************************************************************************** */

// "minivideo_settings.h.in" is the template file
// "minivideo_settings.h" is generated by CMake using the template file

// !!! EVERY TIMES CMake IS RUNNED, THIS FILE WILL BE REGENERATED !!!
// If QMake is used instead of CMake, this file will be leaved empty

/* ************************************************************************** */
#endif // MINIVIDEO_SETTINGS_H
