#-------------------------------------------------------------------------------
# Workflow configuration
#-------------------------------------------------------------------------------

name: "MiniVideo CI builds"
on:
  push:
  pull_request:
  workflow_dispatch:

#-------------------------------------------------------------------------------
# Define application name & version
#-------------------------------------------------------------------------------

env:
  APP_NAME: "MiniVideo"
  APP_VERSION: "0.15"

#-------------------------------------------------------------------------------
# Workflow jobs
#-------------------------------------------------------------------------------

jobs:
  ## GNU/Linux build ###########################################################
  build-linux:
    name: "Linux CI build"
    runs-on: ubuntu-22.04
    steps:
      # Checkout the repository (and submodules)
      - name: Checkout repository (and submodules)
        uses: actions/checkout@v6
        with:
          submodules: recursive

      # Setup env
      - name: Setup env
        run: |
             echo "CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)" >> $GITHUB_ENV
             cmake --version
             ninja --version

      # Build library
      - name: Build library
        run: |
             cd minivideo/
             cmake -B build/ -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=ON -DCMAKE_INSTALL_PREFIX=bin/
             cmake --build build/ --config Release
             cmake --install build/

  ## macOS build ###############################################################
  build-mac:
    name: "macOS CI build"
    runs-on: macos-15
    steps:
      # Checkout the repository (and submodules)
      - name: Checkout repository (and submodules)
        uses: actions/checkout@v6
        with:
          submodules: recursive

      # Setup env
      - name: Setup env
        run: |
             echo "CMAKE_BUILD_PARALLEL_LEVEL=`sysctl -n hw.logicalcpu`" >> $GITHUB_ENV
             cmake --version
             ninja --version

      # Build library
      - name: Build library
        run: |
             cd minivideo/
             cmake -B build/ -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=ON -DCMAKE_INSTALL_PREFIX=bin/
             cmake --build build/ --config Release
             cmake --install build/

  ## Windows build #############################################################
  build-windows:
    name: "Windows CI build"
    runs-on: windows-2022
    steps:
      # Checkout the repository (and submodules)
      - name: Checkout repository (and submodules)
        uses: actions/checkout@v6
        with:
          submodules: recursive

      # Configure MSVC
      - name: Configure MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      # Setup env
      - name: Setup env
        run: |
             cmake --version

      # Build library
      - name: Build library
        run: |
             cd minivideo/
             cmake -B build/ -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=ON -DCMAKE_INSTALL_PREFIX=bin/
             cmake --build build/ --config Release
             cmake --install build/
